create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'student'
);

alter table public.profiles
    add column if not exists role text not null default 'student';

create or replace function public.create_student_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, role)
    values (new.id, 'student')
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists create_student_profile_after_signup on auth.users;
create trigger create_student_profile_after_signup
    after insert on auth.users
    for each row execute procedure public.create_student_profile();

insert into public.profiles (id, role)
select id, 'student' from auth.users
on conflict (id) do nothing;

alter table public.profiles enable row level security;
drop policy if exists profiles_read_own on public.profiles;
create policy profiles_read_own on public.profiles
    for select to authenticated
    using (id = (select auth.uid()));

create table if not exists public.lessons (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null,
    video_url text not null,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now()
);

alter table public.lessons enable row level security;
drop policy if exists lessons_public_read on public.lessons;
create policy lessons_public_read on public.lessons
    for select to anon, authenticated
    using (true);

drop policy if exists lessons_admin_insert on public.lessons;
create policy lessons_admin_insert on public.lessons
    for insert to authenticated
    with check (
        exists (
            select 1 from public.profiles
            where profiles.id = (select auth.uid())
              and profiles.role = 'admin'
        )
    );

drop policy if exists lessons_admin_delete on public.lessons;
create policy lessons_admin_delete on public.lessons
    for delete to authenticated
    using (
        exists (
            select 1 from public.profiles
            where profiles.id = (select auth.uid())
              and profiles.role = 'admin'
        )
    );

grant select on public.lessons to anon, authenticated;
grant insert, delete on public.lessons to authenticated;
grant select on public.profiles to authenticated;
grant usage, select on sequence public.lessons_id_seq to authenticated;

-- بعد إنشاء حساب الأستاذ، غيّر بريده هنا ثم نفّذ هذا التحديث في SQL Editor:
-- update public.profiles
-- set role = 'admin'
-- where id = (select id from auth.users where email = 'teacher@example.com');