create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

alter table public.profiles
    add column if not exists full_name text,
    add column if not exists phone text,
    add column if not exists country text,
    add column if not exists education_level text,
    add column if not exists profile_completed_at timestamptz;

create or replace function public.is_teacher()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select exists (
        select 1 from public.profiles
        where id = (select auth.uid()) and role = 'admin'
    );
$$;

revoke all on function public.is_teacher() from public;
grant execute on function public.is_teacher() to anon, authenticated;

create table if not exists public.courses (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null default '',
    price numeric(10, 2) not null default 0 check (price >= 0),
    currency_code text not null default 'SAR',
    cover_url text,
    published boolean not null default true,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now()
);

alter table public.courses
    add column if not exists currency_code text not null default 'SAR';

create table if not exists public.enrollments (
    id bigint generated by default as identity primary key,
    course_id bigint not null references public.courses(id) on delete cascade,
    student_id uuid not null references auth.users(id) on delete cascade,
    enrolled_at timestamptz not null default now(),
    unique (course_id, student_id)
);

create table if not exists public.course_activation_codes (
    id bigint generated by default as identity primary key,
    course_id bigint not null references public.courses(id) on delete cascade,
    code_hash text not null unique,
    issued_by uuid not null references auth.users(id),
    issued_at timestamptz not null default now(),
    redeemed_by uuid references auth.users(id) on delete set null,
    redeemed_at timestamptz
);

create table if not exists public.platform_settings (
    id boolean primary key default true check (id),
    default_course_fee numeric(10, 2) not null default 0 check (default_course_fee >= 0),
    currency_code text not null default 'SAR',
    updated_at timestamptz not null default now()
);

alter table public.platform_settings
    add column if not exists currency_code text not null default 'SAR';

insert into public.platform_settings (id, default_course_fee)
values (true, 0)
on conflict (id) do nothing;

alter table public.lessons
    add column if not exists course_id bigint references public.courses(id) on delete cascade;

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.enrollments enable row level security;
alter table public.course_activation_codes enable row level security;
alter table public.platform_settings enable row level security;
alter table public.lessons enable row level security;

drop policy if exists profiles_read_own on public.profiles;
create policy profiles_read_own on public.profiles
    for select to authenticated
    using (id = (select auth.uid()));

drop policy if exists profiles_teacher_read on public.profiles;

drop policy if exists profiles_student_update on public.profiles;
create policy profiles_student_update on public.profiles
    for update to authenticated
    using (id = (select auth.uid()) and role = 'student')
    with check (id = (select auth.uid()) and role = 'student');

drop policy if exists courses_public_read on public.courses;
create policy courses_public_read on public.courses
    for select to anon, authenticated
    using (published or (select public.is_teacher()));

drop policy if exists courses_teacher_insert on public.courses;
create policy courses_teacher_insert on public.courses
    for insert to authenticated
    with check ((select public.is_teacher()) and created_by = (select auth.uid()));

drop policy if exists courses_teacher_update on public.courses;
create policy courses_teacher_update on public.courses
    for update to authenticated
    using ((select public.is_teacher()))
    with check ((select public.is_teacher()));

drop policy if exists courses_teacher_delete on public.courses;
create policy courses_teacher_delete on public.courses
    for delete to authenticated
    using ((select public.is_teacher()));

drop policy if exists enrollments_student_or_teacher_read on public.enrollments;
create policy enrollments_student_or_teacher_read on public.enrollments
    for select to authenticated
    using (student_id = (select auth.uid()) or (select public.is_teacher()));

drop policy if exists activation_codes_teacher_read on public.course_activation_codes;
create policy activation_codes_teacher_read on public.course_activation_codes
    for select to authenticated
    using ((select public.is_teacher()));

drop policy if exists platform_settings_teacher_read on public.platform_settings;
create policy platform_settings_teacher_read on public.platform_settings
    for select to authenticated
    using ((select public.is_teacher()));

drop policy if exists platform_settings_teacher_update on public.platform_settings;
create policy platform_settings_teacher_update on public.platform_settings
    for update to authenticated
    using ((select public.is_teacher()))
    with check ((select public.is_teacher()));

drop policy if exists lessons_public_read on public.lessons;
drop policy if exists lessons_enrolled_read on public.lessons;
create policy lessons_enrolled_read on public.lessons
    for select to anon, authenticated
    using (
        course_id is null
        or (select public.is_teacher())
        or exists (
            select 1 from public.enrollments
            where enrollments.course_id = lessons.course_id
              and enrollments.student_id = (select auth.uid())
        )
    );

drop policy if exists lessons_admin_insert on public.lessons;
create policy lessons_admin_insert on public.lessons
    for insert to authenticated
    with check ((select public.is_teacher()) and created_by = (select auth.uid()));

drop policy if exists lessons_admin_delete on public.lessons;
create policy lessons_admin_delete on public.lessons
    for delete to authenticated
    using ((select public.is_teacher()));

grant select on public.courses to anon, authenticated;
grant insert, update, delete on public.courses to authenticated;
grant select on public.enrollments to authenticated;
grant select on public.course_activation_codes to authenticated;
grant select, update on public.platform_settings to authenticated;
grant select on public.profiles to authenticated;
grant update (full_name, phone, country, education_level, profile_completed_at) on public.profiles to authenticated;
grant select on public.lessons to anon;
grant select, insert, delete on public.lessons to authenticated;
grant usage, select on sequence public.courses_id_seq to authenticated;
grant usage, select on sequence public.enrollments_id_seq to authenticated;
grant usage, select on sequence public.course_activation_codes_id_seq to authenticated;

create or replace function public.save_student_profile(
    p_full_name text,
    p_phone text,
    p_country text,
    p_education_level text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if auth.uid() is null then
        raise exception 'يلزم تسجيل الدخول أولاً.';
    end if;
    if coalesce(length(trim(p_full_name)), 0) < 3
        or coalesce(length(trim(p_phone)), 0) < 7
        or coalesce(length(trim(p_country)), 0) < 2
        or coalesce(length(trim(p_education_level)), 0) < 2 then
        raise exception 'يرجى إكمال جميع بيانات الطالب بشكل صحيح.';
    end if;

    update public.profiles
    set full_name = trim(p_full_name),
        phone = trim(p_phone),
        country = trim(p_country),
        education_level = trim(p_education_level),
        profile_completed_at = now()
    where id = auth.uid() and role = 'student';

    if not found then
        raise exception 'لم يتم العثور على حساب طالب صالح.';
    end if;
end;
$$;

create or replace function public.issue_course_activation_code(p_course_id bigint, p_code text)
returns void
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
begin
    if auth.uid() is null or not public.is_teacher() then
        raise exception 'هذه العملية مخصصة للأستاذ.';
    end if;
    if p_code !~ '^[A-Z0-9-]{8,32}$' then
        raise exception 'صيغة رمز التفعيل غير صحيحة.';
    end if;
    if not exists (select 1 from public.courses where id = p_course_id) then
        raise exception 'الدورة غير موجودة.';
    end if;

    insert into public.course_activation_codes (course_id, code_hash, issued_by)
    values (
        p_course_id,
        encode(extensions.digest(upper(trim(p_code)), 'sha256'), 'hex'),
        auth.uid()
    );
end;
$$;

create or replace function public.redeem_course_activation_code(p_course_id bigint, p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
    v_code_id bigint;
    v_course_title text;
    v_student_id uuid := auth.uid();
begin
    if v_student_id is null then
        raise exception 'سجّل الدخول لاستخدام رمز الدورة.';
    end if;
    if not exists (
        select 1 from public.profiles
        where id = v_student_id
          and role = 'student'
          and profile_completed_at is not null
          and full_name is not null
          and phone is not null
          and country is not null
          and education_level is not null
    ) then
        raise exception 'أكمل بيانات حساب الطالب أولاً.';
    end if;
    if exists (
        select 1 from public.enrollments
        where course_id = p_course_id and student_id = v_student_id
    ) then
        raise exception 'أنت مسجل بالفعل في هذه الدورة.';
    end if;

    select id into v_code_id
    from public.course_activation_codes
    where course_id = p_course_id
      and code_hash = encode(extensions.digest(upper(trim(p_code)), 'sha256'), 'hex')
      and redeemed_at is null
    for update;

    if v_code_id is null then
        raise exception 'الرمز غير صحيح أو سبق استخدامه.';
    end if;

    select title into v_course_title
    from public.courses
    where id = p_course_id and published;
    if v_course_title is null then
        raise exception 'الدورة غير متاحة حالياً.';
    end if;

    insert into public.enrollments (course_id, student_id)
    values (p_course_id, v_student_id);

    update public.course_activation_codes
    set redeemed_by = v_student_id,
        redeemed_at = now()
    where id = v_code_id;

    return jsonb_build_object('course_id', p_course_id, 'course_title', v_course_title);
end;
$$;

revoke all on function public.save_student_profile(text, text, text, text) from public;
revoke all on function public.issue_course_activation_code(bigint, text) from public;
revoke all on function public.redeem_course_activation_code(bigint, text) from public;
grant execute on function public.save_student_profile(text, text, text, text) to authenticated;
grant execute on function public.issue_course_activation_code(bigint, text) to authenticated;
grant execute on function public.redeem_course_activation_code(bigint, text) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('course-covers', 'course-covers', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update
set public = true,
    file_size_limit = 5242880,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp'];

drop policy if exists course_covers_public_read on storage.objects;
create policy course_covers_public_read on storage.objects
    for select to anon, authenticated
    using (bucket_id = 'course-covers');

drop policy if exists course_covers_teacher_upload on storage.objects;
create policy course_covers_teacher_upload on storage.objects
    for insert to authenticated
    with check (bucket_id = 'course-covers' and (select public.is_teacher()));

drop policy if exists course_covers_teacher_delete on storage.objects;
create policy course_covers_teacher_delete on storage.objects
    for delete to authenticated
    using (bucket_id = 'course-covers' and (select public.is_teacher()));

notify pgrst, 'reload schema';
